version: "3.9"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      PORT: "8080"
      PG_DSN: "host=pg_currency user=postgres password=secret dbname=currency sslmode=disable TimeZone=Asia/Jakarta"
    ports:
      - "8080:8080"
    depends_on:
      - pg_currency
  
  pg_currency:
    image: postgres:11
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "currency"
      POSTGRES_PASSWORD: "secret"

volumes:
  pg_data: